spring:
  cloud:
    openfeign:
      client:
        config:
          vendor-api:
            connectTimeout: 2100
            readTimeout: 5000
            loggerLevel: full
      compression:
        response:
          enabled: false
      httpclient:
        max-connections: 2000
        max-connections-per-route: 500
        hc5:
          enabled: true
